version: "3"
services:
  peerprep-question-repo:
      container_name: peerprep-question-repo
      image: peerprep-question-repo
      restart: always
      build: .
      ports:
        - "3000:3000"
      links:
        - mongo
  mongo: # We don't need a local Mongo DB for now, so we are connected to Mongo Atlas.
        container_name: mongo
        image: mongo
        volumes:
          - ./data:/data/db
        ports:
          - '27018:27017'