version: "3"
services:
  peerprep-user-manager:
      container_name: peerprep-user-manager
      image: peerprep-user-manager
      restart: always
      build: .
      environment: # Can replace .env file with this
        DB_SCHEMA: postgres
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: postgres      
      ports:
        - "3000:3000" # Will clash with other services, be advised!
      depends_on:
        - postgres
  postgres:
        container_name: postgres
        image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        volumes:
          - postgres-db:/var/lib/postgresql/data
        ports:
          - '5432:5432'

volumes:
  postgres-db: